import { test } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";
import { loginAs } from "./helpers/cookie";

type RoleKey = "admin" | "manager" | "employee";

interface Identity {
  email: string;
  label: string;
  role: RoleKey;
}

interface Route {
  path: string;
  label: string;
  // If unset, the route applies to every identity.  When set, only
  // matching identities visit the route.
  roles?: RoleKey[];
}

// Six identities — three anointed demo users plus three more that exercise
// specific goal-sheet states (Sanjay DRAFT 80%, Aditya SUBMITTED, Kavya fresh).
const IDENTITIES: Identity[] = [
  { email: "admin@demo",  label: "admin-priya",      role: "admin" },
  { email: "mgr@demo",    label: "manager-karthik",  role: "manager" },
  { email: "emp@demo",    label: "employee-riya",    role: "employee" },
  { email: "sanjay@demo", label: "employee-sanjay",  role: "employee" },
  { email: "aditya@demo", label: "employee-aditya",  role: "employee" },
  { email: "kavya@demo",  label: "employee-kavya",   role: "employee" },
];

const VIEWPORTS = [
  { name: "desktop", width: 1280, height: 800 },
  { name: "mobile",  width: 375,  height: 812 },
];

const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
const baseDir = path.join("test-results", "screenshots", stamp);

// Aditya's SUBMITTED sheet ID is dynamic (cuid generated by Prisma at seed
// time).  Resolve once via direct Prisma query so the review-page URL is real
// rather than placeholder.
async function fetchAdityaSheetId(): Promise<string> {
  const prisma = new PrismaClient({
    adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }),
  });
  try {
    const sheet = await prisma.goalSheet.findFirstOrThrow({
      where: { owner: { email: "aditya@demo" }, status: "SUBMITTED" },
      select: { id: true },
    });
    return sheet.id;
  } finally {
    await prisma.$disconnect();
  }
}

test.describe.configure({ mode: "serial" });

test("screenshots", async ({ page }) => {
  const adityaSheetId = await fetchAdityaSheetId();

  const routes: Route[] = [
    { path: "/",                                          label: "home" },
    { path: "/employee/goal-sheet",                       label: "goal-sheet" },
    { path: "/manager/approvals",                         label: "approvals",        roles: ["manager"] },
    { path: `/manager/approvals/${adityaSheetId}`,        label: "approval-review",  roles: ["manager"] },
  ];

  for (const ident of IDENTITIES) {
    await loginAs(page, ident.email);
    for (const viewport of VIEWPORTS) {
      await page.setViewportSize({
        width: viewport.width,
        height: viewport.height,
      });
      for (const route of routes) {
        if (route.roles && !route.roles.includes(ident.role)) continue;
        await page.goto(route.path);
        await page.waitForLoadState("networkidle");
        const dir = path.join(baseDir, ident.label, viewport.name);
        fs.mkdirSync(dir, { recursive: true });
        await page.screenshot({
          path: path.join(dir, `${route.label}.png`),
          fullPage: true,
        });
      }
    }
  }
  console.log(`Screenshots written to ${baseDir}`);
});
