import { test } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";
import { loginAs } from "./helpers/cookie";

type RoleKey = "admin" | "manager" | "employee";

interface Identity {
  email: string;
  label: string;
  role: RoleKey;
}

interface Route {
  path: string;
  label: string;
  // If unset, the route applies to every identity.  When set, only
  // matching identities visit the route.
  roles?: RoleKey[];
}

// Seven identities — three anointed demo users (Priya/Karthik/Riya), three
// more that exercise specific goal-sheet states (Sanjay DRAFT 80%, Aditya
// SUBMITTED, Kavya fresh), and Vikram so the /manager/escalations route
// captures both the empty (Karthik) and populated (Vikram, Kavya's manager)
// states.
const IDENTITIES: Identity[] = [
  { email: "admin@demo",  label: "admin-priya",      role: "admin" },
  { email: "mgr@demo",    label: "manager-karthik",  role: "manager" },
  { email: "vikram@demo", label: "manager-vikram",   role: "manager" },
  { email: "emp@demo",    label: "employee-riya",    role: "employee" },
  { email: "sanjay@demo", label: "employee-sanjay",  role: "employee" },
  { email: "aditya@demo", label: "employee-aditya",  role: "employee" },
  { email: "kavya@demo",  label: "employee-kavya",   role: "employee" },
];

const VIEWPORTS = [
  { name: "desktop", width: 1280, height: 800 },
  { name: "mobile",  width: 375,  height: 812 },
];

const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
const baseDir = path.join("test-results", "screenshots", stamp);

// Aditya's SUBMITTED sheet ID is dynamic (cuid generated by Prisma at seed
// time).  Resolve once via direct Prisma query so the review-page URL is real
// rather than placeholder.
async function fetchAdityaSheetId(): Promise<string> {
  const prisma = new PrismaClient({
    adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }),
  });
  try {
    const sheet = await prisma.goalSheet.findFirstOrThrow({
      where: { owner: { email: "aditya@demo" }, status: "SUBMITTED" },
      select: { id: true },
    });
    return sheet.id;
  } finally {
    await prisma.$disconnect();
  }
}

test.describe.configure({ mode: "serial" });

// Bumped from the 60s default — capturing 28+ pages serially on first-run
// Turbopack compile occasionally squeezes past 60s.
test.setTimeout(180_000);

test("screenshots", async ({ page }) => {
  const adityaSheetId = await fetchAdityaSheetId();

  const routes: Route[] = [
    { path: "/",                                          label: "home" },
    { path: "/employee/goal-sheet",                       label: "goal-sheet" },
    { path: "/employee/check-ins",                        label: "check-ins-index" },
    { path: "/employee/check-in/Q1",                      label: "check-in-q1" },
    { path: "/manager/approvals",                         label: "approvals",        roles: ["manager"] },
    { path: `/manager/approvals/${adityaSheetId}`,        label: "approval-review",  roles: ["manager"] },
    { path: "/manager/check-ins?period=Q1",               label: "check-ins-q1",     roles: ["manager"] },
    { path: "/admin/time-travel",                         label: "time-travel",      roles: ["admin"] },
    { path: "/admin/unlock",                              label: "admin-unlock",     roles: ["admin"] },
    { path: "/admin/audit-log",                           label: "audit-log",        roles: ["admin"] },
    { path: "/admin/escalations",                         label: "admin-escalations",roles: ["admin"] },
    { path: "/manager/escalations",                       label: "manager-escalations", roles: ["manager"] },
    { path: "/reports/completion?period=Q1",              label: "completion",       roles: ["admin", "manager"] },
    { path: "/reports/analytics?period=Q1&tab=qoq",       label: "analytics-qoq",    roles: ["admin", "manager"] },
  ];

  for (const ident of IDENTITIES) {
    await loginAs(page, ident.email);
    for (const viewport of VIEWPORTS) {
      await page.setViewportSize({
        width: viewport.width,
        height: viewport.height,
      });
      for (const route of routes) {
        if (route.roles && !route.roles.includes(ident.role)) continue;
        await page.goto(route.path);
        // domcontentloaded is enough for static screenshots; networkidle was
        // flaky in dev because Turbopack HMR keeps long-poll connections open.
        await page.waitForLoadState("domcontentloaded");
        const dir = path.join(baseDir, ident.label, viewport.name);
        fs.mkdirSync(dir, { recursive: true });
        await page.screenshot({
          path: path.join(dir, `${route.label}.png`),
          fullPage: true,
        });
      }
    }
  }
  console.log(`Screenshots written to ${baseDir}`);
});
